name: Go Test and Deploy Backend

on:
  push:
    branches: ['*']
  pull_request:
    types:
      - closed
      - synchronize
    branches:
      - main
  schedule:
    - cron: '0 10 * * 1'
  workflow_call:
    inputs:
      skipTests:
        description: 'Skip tests, useful when there is a dedicated CI job for tests'
        default: false
        required: false
        type: boolean

jobs:
  test:
    name: Go Test and Format Checks
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      fail-fast: true
      matrix:
        go: ['1.20.x']

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: WWApp-dev-pwd-0
          MYSQL_DATABASE: wwapp_dev_db_test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
          check-latest: true

      - name: Go Format
        run: gofmt -s -w . && git diff --exit-code

      - name: Go Vet
        run: go vet ./...

      - name: Go Tidy
        run: go mod tidy && git diff --exit-code

      - name: Go Mod
        run: go mod download

      - name: Go Mod Verify
        run: go mod verify

      - name: Go Generate
        run: go generate ./... && git diff --exit-code

      - name: Go Build
        run: go build -o /dev/null ./...

      - name: Go Compile Tests
        if: ${{ inputs.skipTests }}
        run: go test -exec /bin/true ./...

      - name: Go Test
        if: ${{ !inputs.skipTests }}
        run: go test -v -count=1 -race -shuffle=on -coverprofile=coverage.txt ./...

      - name: Go Benchmark
        if: ${{ !inputs.skipTests }}
        run: go test -v -shuffle=on -run=- -bench=. -benchtime=1x ./...

  deploy:
    name: Deploy Backend
    needs: test
    if: github.ref == 'refs/heads/main' && github.event_name == 'pull_request' && github.event.pull_request.merged
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        go: ['1.20.x']

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
          check-latest: true

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "$DEPLOYMENT_SECRET_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy to Servers
        run: |
          chmod +x scripts/deploy.sh
          ./scripts/deploy.sh
